### ISSUE TITLE
Style elements in news text

### ISSUE THREAD

**Issue by venkateshshukla** [venkateshshukla/th-editorials-server#1]
Sometimes, the news text contains other HTML elements. For instance for the following piece of html
extracted from `/opinion/op-ed/a-super-visit-in-the-season-of-hope/article7214799.ece`

``` html
<p class="body">
<style>
.fltboxlt {     float:left; }
.fltboxrt {     float:right; }
.borderboxlt { border-left:1px solid #ccc; }
.borderboxrt { border-left:1px solid #ccc; }
.clearboxfix:after {visibility: hidden; display: block; font-size: 0; content: " "; clear: both; height: 0;     }
.lbold {font-weight:bold; }
.thsp-wrap { width:636px; height:295px; text-align:left; background-color:#f8f8f8;}
.thfact-file {  padding:10px; }
.thfact-file h2 { font-size:20px; font-weight:bold; text-transform:none; color:#1f57a5; }
ul.list-b li { margin-bottom:10px; padding-bottom:5px; border-bottom:1px solid #000; }
ul.list-b li span {font-size:25px;padding-bottom:5px;padding-right:10px; margin-top:5px;}
ul.list-b li:last-child { margin-bottom:10px; padding-bottom:5px; border-bottom:none;}
.halfcolart {width:159px;height:295px; box-sizing:border-box;-webkit-box-sizing:border-box;-moz-box-sizing:border-box;}
.halfcolart img { width:159px; height:119px;}
.halfcolimg {width:159px;height:119px; border-radius:50%;}
.halfcoltxt {width:159px;padding:10px;text-align: left; background-color:#f8f8f8;box-sizing:border-box;-webkit-box-sizing:border-box;-moz-box-sizing:border-box;}
.halfcoltxt h3 {text-transform:none;font-size:18px;}
.halfcoltxt p {font-size:13px;}
.halfcoltxt:hover { background: #eee; cursor: pointer;}</style>
</p>
```

we get the following in the text.

``` css
.fltboxlt {     float:left; }
.fltboxrt {     float:right; }
.borderboxlt { border-left:1px solid #ccc; }
.borderboxrt { border-left:1px solid #ccc; }
.clearboxfix:after {visibility: hidden; display: block; font-size: 0; content: " "; clear: both; height: 0;     }
.lbold {font-weight:bold; }
.thsp-wrap { width:636px; height:295px; text-align:left; background-color:#f8f8f8;}
.thfact-file {  padding:10px; }
.thfact-file h2 { font-size:20px; font-weight:bold; text-transform:none; color:#1f57a5; }
ul.list-b li { margin-bottom:10px; padding-bottom:5px; border-bottom:1px solid #000; }
ul.list-b li span {font-size:25px;padding-bottom:5px;padding-right:10px; margin-top:5px;}
ul.list-b li:last-child { margin-bottom:10px; padding-bottom:5px; border-bottom:none;}
.halfcolart {width:159px;height:295px; box-sizing:border-box;-webkit-box-sizing:border-box;-moz-box-sizing:border-box;}
.halfcolart img { width:159px; height:119px;}
.halfcolimg {width:159px;height:119px; border-radius:50%;}
.halfcoltxt {width:159px;padding:10px;text-align: left; background-color:#f8f8f8;box-sizing:border-box;-webkit-box-sizing:border-box;-moz-box-sizing:border-box;}
.halfcoltxt h3 {text-transform:none;font-size:18px;}
.halfcoltxt p {font-size:13px;}
.halfcoltxt:hover { background: #eee; cursor: pointer;}
```
